version: '3.6'
services:
  app:
    image: jasonmccallister/laravel-docker-preset
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file: .env
    volumes:
      - .:/var/www/html:cached
      # uncomment if using laravel passport
      # - ./storage/oauth-private.key:/var/www/html/storage/oauth-private.key
      # - ./storage/oauth-public.key:/var/www/html/storage/oauth-public.key
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  queue:
    image: jasonmccallister/laravel-docker-preset
    command: ["php", "artisan", "queue:work", "--tries=1"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
      # uncomment if using laravel passport
      # - ./storage/oauth-private.key:/var/www/html/storage/oauth-private.key
      # - ./storage/oauth-public.key:/var/www/html/storage/oauth-public.key
  redis:
    image: redis
    ports:
     - 6379:6379
volumes:
  db_data:
